# Generated by Django 4.0.1 on 2022-02-06 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('R', 'READ'), ('RW', 'READ&WRITE')], default='R', max_length=2)),
                ('role', models.CharField(choices=[('D', 'DÉVELOPPEUR'), ('PW', 'PROJECT OWNER')], default='D', max_length=2)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contrib', to='projects.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contrib', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
